version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - pip install pdm
    post_install:
      - pdm use -f $READTHEDOCS_VIRTUALENV_PATH
      - pdm install
    pre_build:
      # Generate the Sphinx configuration for this Jupyter Book so it builds.
      - "jupyter-book config sphinx book"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
      - sphinx

sphinx:
  configuration: book/conf.py
  builder: html
  fail_on_warning: true
